[package]
name = "qr_code_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.6.0"
image = "0.23.0"
qrcode = "0.12.0"
regex = "1.10.4"
serde = { version = "1.0.203", features = ["derive"] }
